// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prid1920_g01.Models;

namespace prid1920_g01.Migrations
{
    [DbContext(typeof(Prid1920_g01Context))]
    partial class Prid1920_g01ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("prid1920_g01.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("Reputation");

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Email = "Ben@epfc.eu",
                            FirstName = "Ben",
                            LastName = "Penelle",
                            Password = "Ben",
                            Pseudo = "Benito",
                            Reputation = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 11,
                            Email = "Bruno@epfc.eu",
                            FirstName = "Bru",
                            LastName = "Lacroix",
                            Password = "Bruno",
                            Pseudo = "Bruno",
                            Reputation = 1,
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
